// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH9VW0MEO3GXOc1luH4xrWREw0jiLpXeU',
    appId: '1:286898387679:web:96e3ffab3d12f0984c476a',
    messagingSenderId: '286898387679',
    projectId: 'maintenance-81604',
    authDomain: 'maintenance-81604.firebaseapp.com',
    storageBucket: 'maintenance-81604.appspot.com',
    measurementId: 'G-VZLVQ05BDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR6QEmnYi2TKE1cBd7XsLw37QNNWZrJyU',
    appId: '1:286898387679:android:5d84fd719f34b99b4c476a',
    messagingSenderId: '286898387679',
    projectId: 'maintenance-81604',
    storageBucket: 'maintenance-81604.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJLFq7-18kQ0I2fqmwOUc75TDQK7_XkS4',
    appId: '1:286898387679:ios:68a493faad7975474c476a',
    messagingSenderId: '286898387679',
    projectId: 'maintenance-81604',
    storageBucket: 'maintenance-81604.appspot.com',
    iosBundleId: 'com.example.pfe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJLFq7-18kQ0I2fqmwOUc75TDQK7_XkS4',
    appId: '1:286898387679:ios:68a493faad7975474c476a',
    messagingSenderId: '286898387679',
    projectId: 'maintenance-81604',
    storageBucket: 'maintenance-81604.appspot.com',
    iosBundleId: 'com.example.pfe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH9VW0MEO3GXOc1luH4xrWREw0jiLpXeU',
    appId: '1:286898387679:web:c1605dd598555d4e4c476a',
    messagingSenderId: '286898387679',
    projectId: 'maintenance-81604',
    authDomain: 'maintenance-81604.firebaseapp.com',
    storageBucket: 'maintenance-81604.appspot.com',
    measurementId: 'G-HEQW99Y3RY',
  );
}
